name: CI

on:
    push:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Elixir
              uses: erlef/setup-beam@v1
              with:
                elixir-version: '1.17.2'

            - name: Install Dependencies
              run: mix deps.get
            
            - name: Build Project
              run: mix compile
